AZURE_OPENAI_API_KEY2 = ""
AZURE_OPENAI_EMBEDDING_MODEL2 = "text-embedding-ada-002"
AZURE_OPENAI_ENDPOINT2 = "https://endpoint_name.openai.azure.com"
AZURE_OPENAI_DEPLOYMENT2 = "gpt-4o"
AZURE_OPENAI_API_VERSION2 = "2024-05-01-preview"
AZURE_OPENAI_API_TYPE2 = "azure"

REDIS_URL = "redis://host_ip:6379"
REDIS_HOST = "host_ip"

LLAMA_MODEL = "llama3.1"
LLAMA_BASE_URL = "host_ip"
NEO4J_AURA_YT = "neo4j+s://instance_id.databases.neo4j.io"
NEO4J_AURA_YT_USER = "neo4j"
NEO4J_AURA_YT_PASSWORD = "password"


NEO4J_PORT = "7687"
NEO4J_DB = "neo4j"
NEO4J_HOST = "instance_id.databases.neo4j.io"
NEO4J_URI="neo4j+s://instance_id.databases.neo4j.io"
NEO4J_USER="neo4j"
NEO4J_PASSWORD="password"

NEO4J_BLOOM_URL="https://bloom.neo4j.io/index.html?connectURL=instance_id.databases.neo4j.io&perspective=demo&run=true&search="